yarnPath: ".yarn/releases/yarn-berry.cjs"
npmScopes:
  gsap:
    npmRegistryServer: https://npm.greensock.com
#    npmAlwaysAuth: true
npmRegistries:
  //npm.greensock.com:
    #    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}
